export const typeIcons = {
    bug: "src/assets/icons/bug.svg",
    dark: "src/assets/icons/dark.svg",
    dragon: "src/assets/icons/dragon.svg",
    electric: "src/assets/icons/electric.svg",
    fairy: "src/assets/icons/fairy.svg",
    fighting: "src/assets/icons/fighting.svg",
    fire: "src/assets/icons/fire.svg",
    ghost: "src/assets/icons/ghost.svg",
    ice: "src/assets/icons/ice.svg",
    normal: "src/assets/icons/normal.svg",
    poison: "src/assets/icons/poison.svg",
    psychic: "src/assets/icons/psychic.svg",
    rock: "src/assets/icons/rock.svg",
    steel: "src/assets/icons/steel.svg",
    water: "src/assets/icons/water.svg",
    grass: "src/assets/icons/grass.svg",
};